### PR TITLE
Direct COM1 to file to improve boot time.

### PR DESCRIPTION
**Pull request by edwinpjacques**
# Improve Boot Time on VirtualBox 6 (maybe others too?)

Boot time in VirtualBox 6 was taking 30m or so for the routing engine.
Found that the problem was related to COM1 not being connected to anything.
Connected it to a file, and now the light qfx boots in about a minute on my machine.
Made the change in all Vagrantfiles and tested to make sure it comes up.

This change only helps, hopefully a quick one to approve.

### CODE REVIEW

**Comment by edwinpjacques** [comment]
Hi @grigorenkoae was hoping you could take a look at this?  Thanks!

**Comment by edwinpjacques** [comment]
Closes #36

**Comment by edwinpjacques** [comment]
@trmccart would you mind to approve this?  It make Vagrant usable again for many OS X users.  Thank you.

**Comment by edwinpjacques** [comment]
@aburston can you try this on Windows please to be safe?  I tested all the Vagrantfiles on OSX.

**Comment by aburston** [comment]
> @aburston can you try this on Windows please to be safe? I tested all the Vagrantfiles on OSX.

Will do, could you please assign this issue to me.

**Comment by edwinpjacques** [comment]
@aburston I don't have permission to do that.  Not sure who maintains this.  Activity seems a bit light.

**Comment by aburston** [comment]
@edwinpjacques looks like @trmccart is the person who last merged code, so we could ask him once I have tested this.

**Comment by edwinpjacques** [comment]
@aburston hold on, let me try another tweak to avoid having to write a log file at all.  The hard part is supporting Windows since I have to set the log file to NUL instead of /dev/null.  Should be doable though.

**Comment by aburston** [comment]
@edwinpjacques Don't try create files for the "National University of Lesotho", tried that doesn't work out well in windows.

**Comment by edwinpjacques** [comment]
@aburston I replaced the assignment of re_log with a conditional that works on OS X, Linux & should work fine on Windows.

**Pull request merged**
